create database customer_behavior;
use customer_behavior;
select * from customer;
 
 -- ? Q1. List all distinct product categories.
 select distinct category from customer;
 
 
  -- ? Q2. Calculate the total revenue generated from all purchases.
 select sum(purchase_amount) as Total_Revenue from customer;
 
 
  -- ? Q3. Find the average purchase value.
  select avg(purchase_amount) as average_purchase_value from customer;
  
  
   -- ? Q4. Identify the top 5 most purchased products.
   select item_purchased, 
	count(item_purchased) as Total_Sales 
from customer 
group by item_purchased
order by Total_Sales desc;
   
   
 -- ? Q5. Identify customers who made more than 5 purchases.  
select customer_id ,
	previous_purchases
from customer
where previous_purchases > 5 ;
   
-- ? Q6. What is the total revenue generated by male vs. female customers?

select gender, 
	sum(purchase_amount) as revenue 
from customer 
group by gender;


 -- ? Q7. Which customers used a discount but still spent more than the average purchase amount?
 
select customer_id,
	purchase_amount 
from customer 
where discount_applied = 'yes' 
and purchase_amount >= (select avg(purchase_amount) from customer);


-- ? Q8. Which are the top 5 products with the highest average review rating?

select item_purchased, 
	avg(review_rating) as avg_rating 
from customer 
group by item_purchased 
order by avg_rating desc limit 5;


-- ? Q9. Compare the average Purchase Amounts between Standard and Express Shipping.
 
select shipping_type, 
	avg(purchase_amount) 
from customer
where shipping_type in ('standard', 'express') 
group by shipping_type;


-- ? Q10. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.]

select subscription_status,
	count(subscription_status), 
    avg(purchase_amount), 
    sum(purchase_amount) 
from customer
group by subscription_status;


-- ? Q11. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
	100.0* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- ? Q12. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases

select customer_id,
	previous_purchases, 
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyas'
    end as customer_segment
from customer;


-- ? Q13. What are the top 3 most purchased products within each category? 

with item_counts as (
select category,
	item_purchased,
    count(customer_id) as total_orders,
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;


-- ? Q14. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, 
	count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status;


-- Q15. What is the revenue contribution of each age group? 

select age_group, 
	sum(purchase_amount) as Total_revenue
from customer
group by age_group;